django/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('polls.urls',namespace="polls")),
)

django/polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/detail/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^vote/$', views.vote, name='vote'),
    url(r'^add/$', views.add, name='add'),
   # url(r'^(?P<pk>\d+)/change/$', views.update_list, name='update_list'),
    url(r'^delete/(?P<pk>\d+)$', views.delete, name='delete'),
    url(r'^edit/(?P<pk>\d+)$', views.edit, name='edit'),
    url(r'^redirect_to_original/(?P<pk>\d+)$', views.redirect_to_original, name='redirect_to_original'),
    url(r'^logout_view/$', views.logout_view, name='logout_view'),
)

django/polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):              # __unicode__ on Python 2
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

#preferences
class Options(models.Model):
    user = models.ForeignKey(User)
    option_college = models.CharField(max_length=100)
    option_branch = models.CharField(max_length=200)
    option_code = models.CharField(max_length=10)
    #votes = models.IntegerField(default=0)
    def __str__(self):              # __unicode__ on Python 2
        return self.choice_code

class Preferences(models.Model):
	pref_college = models.CharField(max_length=100)
	pref_branch = models.CharField(max_length=200)
	pref_code = models.CharField(max_length=10)
	def __str__(self):              # __unicode__ on Python 2
		return self.pref_code
	

django/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render
from django.template import RequestContext, loader
from django.http import Http404
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from polls.models import Question,Options,Preferences

# Create your views here.
'''
def index(request):
    
    template = loader.get_template('polls/index.html')
    context = RequestContext(request, {
        
        })
    return HttpResponse(template.render(context))
'''
'''def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404
    return render(request, 'polls/\detail.html', {'question': question})
'''
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = User
    template_name = 'polls/detail.html'
    
class ResultsView(generic.ListView):
	model = User
	template_name = 'polls/results.html'
	context_object_name = 'prefsl'
	def get_queryset(self):
		return  Preferences.objects
	
	


'''def results(request, user_id):
    
    return render(request, 'polls/results.html', {'user': user})
'''
def vote(request):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(username=username, password=password)	
	if user is not None:
		login(request,user)
		return HttpResponseRedirect(reverse('polls:results', args=(user.id,)))
		
	else:
		return render(request, 'polls/index.html', {
	         'error_message': 'invalid username or password',
		})
		
def add(request):
	#p = get_object_or_404(Preferences)
	now_user=request.user
	pr = request.POST['Preferences']
	al = Preferences.objects.get(id=pr)
	flag = True
	for p in now_user.options_set.all():
		if p.option_code == al.pref_code:
			flag = False
			
	
	if flag==True :
		now_user.options_set.create(option_college=al.pref_college,option_branch=al.pref_branch,option_code=al.pref_code,)
	
	
	return HttpResponseRedirect(reverse('polls:results', args=(now_user.id,)))

def delete(request,pk):
	p=get_object_or_404(Options, pk=pk)
	now_user=request.user
	obj = now_user.options_set.get(pk=pk)
	obj.delete()
	return HttpResponseRedirect(reverse('polls:results', args=(now_user.id,)))
	
	
def edit(request,pk):
	p=get_object_or_404(Options, pk=pk)
	now_user=request.user
	obj = now_user.options_set.get(pk=pk)
	return render(request, 'polls/edit.html',{
			'a' : pk ,
			'ch' : obj ,
			'prefsl' : Preferences.objects ,
		})
	
'''
def update_list(request):
	now_user=request.user
	get = request.POST['change_of']
	a = get[0]
	b = get[1]
	
	obj = now_user.options_set.get(id=a)
	
	if b == 1:
		return HttpResponseRedirect(reverse('polls:results', args=(now_user.id,)))
	elif b == 2:
		obj.delete()
		return HttpResponseRedirect(reverse('polls:results', args=(now_user.id,)))
	
	elif b == 3:
		return render(request, 'polls/edit.html',{
			'a' : a ,
			'ch' : 
			'prefsl' : Preferences.objects ,
		})
'''	
def redirect_to_original(request,pk):
	now_user=request.user
	
	p=get_object_or_404(Options, pk=pk)
	x = request.POST['Preferences']
	b = Preferences.objects.get(id=x)
	
	old = now_user.options_set.get(id=pk)
	flag = True
	#new = now_user.options_set.get(id=x)
	for q in now_user.options_set.all():
		if q.option_code == b.pref_code:
			z = False
	if z == True:	
		old.option_college = b.pref_college
		old.option_code = b.pref_code
		old.option_branch = b.pref_branch
		old.save()
		
	return HttpResponseRedirect(reverse('polls:results', args=(now_user.id,)))

def logout_view(request):
	logout(request)
	return render(request, 'polls/index.html')
	
    
	
'''p = get_object_or_404(Question, pk=question_id)
	try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(user.id,)))'''

django/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

django/templates/polls/edit.html
<div align="center">
<h2 style="color:#AF0912">Edit Your selected preference</h2>
<form action="{% url 'polls:redirect_to_original' a %}" method = "post">
{% csrf_token %}
<select name="Preferences">
{% for prefs in prefsl.all %}
	<option name='preferences' value="{{ prefs.id }}">{{ prefs.pref_college }}, {{ prefs.pref_branch }}</option>
{% endfor %}
</select>
<input type="submit" value="Submit"/>
</form>
</div>

django/templates/polls/index.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div align="center" style="margin-top:100px;border:1px solid blue;
background-color:grey;">
<h2 style="color:blue">Login Portal</h2>
<form action="{% url 'polls:vote' %}" method="post">
		{% csrf_token %}
		<table>
            <tr>
                <td>Username :</td>
                <td><input id="username" maxlength="200" name="username" type="text" /></td>
            </tr>
            <tr>
                <td>Password :</td>
                <td><input id="id_password" maxlength="200" name="password" type="password" /></td>
            </tr>
       </table>

		<input type="submit" value="LOGIN">
		</form> 
</div>

django/templates/polls/results.html
<html>
<div align="right"><a href={% url 'polls:logout_view' %}>LOGOUT</a></div>
<div align="center" >
<h1 style="color:green">Welcome {{user.username}}</h1>
<h2>Please select your preferences from here</h2>
<form action="{% url 'polls:add' %}" method = "post">
{% csrf_token %}
<select name="Preferences">

{% for prefs in prefsl.all %}
	<option name='preferences' value={{ prefs.id }}>{{ prefs.pref_college }}, {{ prefs.pref_branch }}</option>
{% endfor %}
</select>
<input type="submit" value="Add"/>
</form>

<h2>Your Preferred choices :</h2>

</div>
<div align="center">
<table>
{% for p in user.options_set.all  %}


<tr>
<td>{{ p.option_college }} , {{ p.option_branch }}, {{p.option_code}}</td>
<td><a href="{% url 'polls:delete' p.pk %}">DELETE</a>
	<a href="{% url 'polls:edit' p.pk %}">EDIT</a></td>
</tr>

{% csrf_token %}
	
<!--input type="submit" value="Make changes"/>
</form>-->
{% endfor %}
</table>
</div>
</html>